### ISSUE TITLE
question about preprocessing

### ISSUE THREAD

**Issue by wanglilier925** [anesdo/ICH_DETECTION_PROGNOSIS_2D3D#1]
hello, anesdo,

when I tried to run your code, I have some problems need your help about image preprocessing, how to get the file:  
path_image = '/home/jovyan/IMAGE_PREPROCESSING_2D_3D/DICOM/',
dicom='9/13016/2/',

could you give me a hint?

**Comment by anesdo** [comment]
Hi wanglilier925, 
You need to use your data. 
- path_image : it is where you have your dicoms images.
- dicom: name of the dicom you want to use.

In my notebook I chose 9/13016/2/ dicom but you should use your path and your dicom. 

Thank you for asking.
Anna Esteve
